[package]
name = "flakedb"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.22"
memchr = "2.4.1"
structopt = "0.3.25"
thiserror = "1.0.30"

[dev-dependencies]
assert_fs = "1.0.6"
rexpect = "0.4.0"
test-case = "2.2.1"
